import { createContext } from "react";

const dummyWorkItem_activityCalendar = {
  accessRight: {
    CosemClient1: {
      attribute: [
        "Get",
        "GetSet",
        "GetSet",
        "GetSet",
        "GetSet",
        "GetSet",
        "GetSet",
        "GetSet",
        "GetSet",
        "GetSet",
      ],
      method: ["Act"],
    },
    CosemClient102: {
      attribute: [
        "NA",
        "NA",
        "NA",
        "NA",
        "NA",
        "Set",
        "Set",
        "Set",
        "Set",
        "Set",
      ],
      method: ["Act"],
    },
    CosemClient111: {
      attribute: [
        "Get",
        "GetSet",
        "GetSet",
        "GetSet",
        "GetSet",
        "GetSet",
        "GetSet",
        "GetSet",
        "GetSet",
        "GetSet",
      ],
      method: ["Act"],
    },
    CosemClient112: {
      attribute: [
        "Get",
        "Get",
        "Get",
        "Get",
        "Get",
        "Get",
        "Get",
        "Get",
        "Get",
        "Get",
      ],
      method: ["NA"],
    },
    CosemClient120: {
      attribute: ["NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA"],
      method: ["NA"],
    },
    CosemClient16: {
      attribute: ["NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA"],
      method: ["NA"],
    },
  },
  attribute: [
    {
      _dtype: "OctetStringDTO",
      arrayTemplate: null,
      children: [],
      comment: "",
      defaultValue: "0,4,13,0,0,255",
      dtypeChoices: null,
      enumChoices: {},
      hidden: false,
      id: "1",
      isArray: false,
      isChoice: false,
      isConfigurable: false,
      is_ASCII: [],
      is_ByteArray: [],
      is_VisibleString: [],
      maxValue: 6,
      minValue: 6,
      modifier: "",
      parent: null,
      reference: "",
      section: "NLR",
      title: "logical_name",
    },
    {
      _dtype: "OctetStringDTO",
      arrayTemplate: null,
      children: [],
      comment: "",
      defaultValue: "115,101,97,115,111,110,95,49",
      dtypeChoices: null,
      enumChoices: {},
      hidden: false,
      id: "2",
      isArray: false,
      isChoice: false,
      isConfigurable: false,
      is_ASCII: [],
      is_ByteArray: [],
      is_VisibleString: [],
      maxValue: 8,
      minValue: 8,
      modifier: "",
      parent: null,
      reference: "",
      section: "NLR",
      title: "calendar_name_active",
    },
    {
      _dtype: "Array",
      arrayTemplate: {
        _dtype: "Structure",
        arrayTemplate: null,
        children: [
          {
            _dtype: "OctetStringDTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "115,101,97,115,111,110,95,49",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-0",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: 8,
            minValue: 8,
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "OctetStringDTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "255,255,1,1,255,0,0,0,0,128,0,0",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-1",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: 12,
            minValue: 12,
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "OctetStringDTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "119,101,101,107,95,48,48,49",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-2",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: 8,
            minValue: 8,
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
        ],
        comment: "",
        defaultValue: null,
        dtypeChoices: null,
        enumChoices: {},
        hidden: false,
        id: "None-0",
        isArray: false,
        isChoice: false,
        isConfigurable: false,
        is_ASCII: [],
        is_ByteArray: [],
        is_VisibleString: [],
        maxValue: null,
        minValue: null,
        modifier: "",
        parent: null,
        reference: "",
        section: "NLR",
        title: null,
      },
      children: [
        {
          _dtype: "Structure",
          arrayTemplate: null,
          children: [
            {
              _dtype: "OctetStringDTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "115,101,97,115,111,110,95,49",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "3-0-0",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: 8,
              minValue: 8,
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "OctetStringDTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "255,255,1,1,255,0,0,0,0,128,0,0",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "3-0-1",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: 12,
              minValue: 12,
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "OctetStringDTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "119,101,101,107,95,48,48,49",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "3-0-2",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: 8,
              minValue: 8,
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
          ],
          comment: "",
          defaultValue: null,
          dtypeChoices: null,
          enumChoices: {},
          hidden: false,
          id: "3-0",
          isArray: false,
          isChoice: false,
          isConfigurable: false,
          is_ASCII: [],
          is_ByteArray: [],
          is_VisibleString: [],
          maxValue: null,
          minValue: null,
          modifier: "",
          parent: null,
          reference: "",
          section: "NLR",
          title: null,
        },
      ],
      comment: "",
      defaultValue: null,
      dtypeChoices: null,
      enumChoices: {},
      hidden: false,
      id: "3",
      isArray: false,
      isChoice: false,
      isConfigurable: false,
      is_ASCII: [],
      is_ByteArray: [],
      is_VisibleString: [],
      maxValue: "12",
      minValue: "1",
      modifier: "",
      parent: null,
      reference: "",
      section: "NLR",
      title: "season_profile_active",
    },
    {
      _dtype: "Array",
      arrayTemplate: {
        _dtype: "Structure",
        arrayTemplate: null,
        children: [
          {
            _dtype: "OctetStringDTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "119,101,101,107,95,48,48,49",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-0",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: 8,
            minValue: 8,
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "Unsigned8DTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "1",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-1",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: "12",
            minValue: "1",
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "Unsigned8DTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "1",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-2",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: "12",
            minValue: "1",
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "Unsigned8DTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "1",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-3",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: "12",
            minValue: "1",
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "Unsigned8DTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "1",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-4",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: "12",
            minValue: "1",
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "Unsigned8DTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "1",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-5",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: "12",
            minValue: "1",
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "Unsigned8DTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "1",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-6",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: "12",
            minValue: "1",
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "Unsigned8DTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "1",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-7",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: "12",
            minValue: "1",
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
        ],
        comment: "",
        defaultValue: null,
        dtypeChoices: null,
        enumChoices: {},
        hidden: false,
        id: "None-0",
        isArray: false,
        isChoice: false,
        isConfigurable: false,
        is_ASCII: [],
        is_ByteArray: [],
        is_VisibleString: [],
        maxValue: null,
        minValue: null,
        modifier: "",
        parent: null,
        reference: "",
        section: "NLR",
        title: null,
      },
      children: [
        {
          _dtype: "Structure",
          arrayTemplate: null,
          children: [
            {
              _dtype: "OctetStringDTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "119,101,101,107,95,48,48,49",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "4-0-0",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: 8,
              minValue: 8,
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "Unsigned8DTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "1",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "4-0-1",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: "12",
              minValue: "1",
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "Unsigned8DTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "1",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "4-0-2",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: "12",
              minValue: "1",
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "Unsigned8DTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "1",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "4-0-3",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: "12",
              minValue: "1",
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "Unsigned8DTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "1",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "4-0-4",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: "12",
              minValue: "1",
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "Unsigned8DTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "1",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "4-0-5",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: "12",
              minValue: "1",
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "Unsigned8DTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "1",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "4-0-6",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: "12",
              minValue: "1",
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "Unsigned8DTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "1",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "4-0-7",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: "12",
              minValue: "1",
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
          ],
          comment: "",
          defaultValue: null,
          dtypeChoices: null,
          enumChoices: {},
          hidden: false,
          id: "4-0",
          isArray: false,
          isChoice: false,
          isConfigurable: false,
          is_ASCII: [],
          is_ByteArray: [],
          is_VisibleString: [],
          maxValue: null,
          minValue: null,
          modifier: "",
          parent: null,
          reference: "",
          section: "NLR",
          title: null,
        },
      ],
      comment: "",
      defaultValue: null,
      dtypeChoices: null,
      enumChoices: {},
      hidden: false,
      id: "4",
      isArray: false,
      isChoice: false,
      isConfigurable: false,
      is_ASCII: [],
      is_ByteArray: [],
      is_VisibleString: [],
      maxValue: "12",
      minValue: "1",
      modifier: "",
      parent: null,
      reference: "",
      section: "NLR",
      title: "week_profile_table_active",
    },
    {
      _dtype: "Array",
      arrayTemplate: {
        _dtype: "Structure",
        arrayTemplate: null,
        children: [
          {
            _dtype: "Unsigned8DTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "1",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-0",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: "12",
            minValue: "1",
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "Array",
            arrayTemplate: {
              _dtype: "Structure",
              arrayTemplate: null,
              children: [
                {
                  _dtype: "OctetStringDTO",
                  arrayTemplate: null,
                  children: [],
                  comment: "",
                  defaultValue: "0,0,0,0",
                  dtypeChoices: null,
                  enumChoices: {},
                  hidden: false,
                  id: "None-0-0",
                  isArray: false,
                  isChoice: false,
                  isConfigurable: false,
                  is_ASCII: [],
                  is_ByteArray: [],
                  is_VisibleString: [],
                  maxValue: 4,
                  minValue: 4,
                  modifier: "",
                  parent: null,
                  reference: "",
                  section: "NLR",
                  title: null,
                },
                {
                  _dtype: "OctetStringDTO",
                  arrayTemplate: null,
                  children: [],
                  comment: "",
                  defaultValue: "0,1,10,0,100,255",
                  dtypeChoices: null,
                  enumChoices: {},
                  hidden: false,
                  id: "None-0-1",
                  isArray: false,
                  isChoice: false,
                  isConfigurable: false,
                  is_ASCII: [],
                  is_ByteArray: [],
                  is_VisibleString: [],
                  maxValue: 6,
                  minValue: 6,
                  modifier: "",
                  parent: null,
                  reference: "",
                  section: "NLR",
                  title: "Contract1TarifficationScriptTable",
                },
                {
                  _dtype: "Unsigned16DTO",
                  arrayTemplate: null,
                  children: [],
                  comment: "",
                  defaultValue: "0",
                  dtypeChoices: null,
                  enumChoices: {},
                  hidden: false,
                  id: "None-0-2",
                  isArray: false,
                  isChoice: false,
                  isConfigurable: false,
                  is_ASCII: [],
                  is_ByteArray: [],
                  is_VisibleString: [],
                  maxValue: "9",
                  minValue: "0",
                  modifier: "",
                  parent: null,
                  reference: "",
                  section: "NLR",
                  title: null,
                },
              ],
              comment: "",
              defaultValue: null,
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "None-0",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: null,
              minValue: null,
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            children: [
              {
                _dtype: "Structure",
                arrayTemplate: null,
                children: [
                  {
                    _dtype: "OctetStringDTO",
                    arrayTemplate: null,
                    children: [],
                    comment: "",
                    defaultValue: "0,0,0,0",
                    dtypeChoices: null,
                    enumChoices: {},
                    hidden: false,
                    id: "None-0-1-0-0",
                    isArray: false,
                    isChoice: false,
                    isConfigurable: false,
                    is_ASCII: [],
                    is_ByteArray: [],
                    is_VisibleString: [],
                    maxValue: 4,
                    minValue: 4,
                    modifier: "",
                    parent: null,
                    reference: "",
                    section: "NLR",
                    title: null,
                  },
                  {
                    _dtype: "OctetStringDTO",
                    arrayTemplate: null,
                    children: [],
                    comment: "",
                    defaultValue: "0,1,10,0,100,255",
                    dtypeChoices: null,
                    enumChoices: {},
                    hidden: false,
                    id: "None-0-1-0-1",
                    isArray: false,
                    isChoice: false,
                    isConfigurable: false,
                    is_ASCII: [],
                    is_ByteArray: [],
                    is_VisibleString: [],
                    maxValue: 6,
                    minValue: 6,
                    modifier: "",
                    parent: null,
                    reference: "",
                    section: "NLR",
                    title: "Contract1TarifficationScriptTable",
                  },
                  {
                    _dtype: "Unsigned16DTO",
                    arrayTemplate: null,
                    children: [],
                    comment: "",
                    defaultValue: "0",
                    dtypeChoices: null,
                    enumChoices: {},
                    hidden: false,
                    id: "None-0-1-0-2",
                    isArray: false,
                    isChoice: false,
                    isConfigurable: false,
                    is_ASCII: [],
                    is_ByteArray: [],
                    is_VisibleString: [],
                    maxValue: "9",
                    minValue: "0",
                    modifier: "",
                    parent: null,
                    reference: "",
                    section: "NLR",
                    title: null,
                  },
                ],
                comment: "",
                defaultValue: null,
                dtypeChoices: null,
                enumChoices: {},
                hidden: false,
                id: "None-0-1-0",
                isArray: false,
                isChoice: false,
                isConfigurable: false,
                is_ASCII: [],
                is_ByteArray: [],
                is_VisibleString: [],
                maxValue: null,
                minValue: null,
                modifier: "",
                parent: null,
                reference: "",
                section: "NLR",
                title: null,
              },
            ],
            comment: "",
            defaultValue: null,
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-1",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: "24",
            minValue: "1",
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
        ],
        comment: "",
        defaultValue: null,
        dtypeChoices: null,
        enumChoices: {},
        hidden: false,
        id: "None-0",
        isArray: false,
        isChoice: false,
        isConfigurable: false,
        is_ASCII: [],
        is_ByteArray: [],
        is_VisibleString: [],
        maxValue: null,
        minValue: null,
        modifier: "",
        parent: null,
        reference: "",
        section: "NLR",
        title: null,
      },
      children: [
        {
          _dtype: "Structure",
          arrayTemplate: null,
          children: [
            {
              _dtype: "Unsigned8DTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "1",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "5-0-0",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: "12",
              minValue: "1",
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "Array",
              arrayTemplate: {
                _dtype: "Structure",
                arrayTemplate: null,
                children: [
                  {
                    _dtype: "OctetStringDTO",
                    arrayTemplate: null,
                    children: [],
                    comment: "",
                    defaultValue: "0,0,0,0",
                    dtypeChoices: null,
                    enumChoices: {},
                    hidden: false,
                    id: "None-0-0",
                    isArray: false,
                    isChoice: false,
                    isConfigurable: false,
                    is_ASCII: [],
                    is_ByteArray: [],
                    is_VisibleString: [],
                    maxValue: 4,
                    minValue: 4,
                    modifier: "",
                    parent: null,
                    reference: "",
                    section: "NLR",
                    title: null,
                  },
                  {
                    _dtype: "OctetStringDTO",
                    arrayTemplate: null,
                    children: [],
                    comment: "",
                    defaultValue: "0,1,10,0,100,255",
                    dtypeChoices: null,
                    enumChoices: {},
                    hidden: false,
                    id: "None-0-1",
                    isArray: false,
                    isChoice: false,
                    isConfigurable: false,
                    is_ASCII: [],
                    is_ByteArray: [],
                    is_VisibleString: [],
                    maxValue: 6,
                    minValue: 6,
                    modifier: "",
                    parent: null,
                    reference: "",
                    section: "NLR",
                    title: "Contract1TarifficationScriptTable",
                  },
                  {
                    _dtype: "Unsigned16DTO",
                    arrayTemplate: null,
                    children: [],
                    comment: "",
                    defaultValue: "0",
                    dtypeChoices: null,
                    enumChoices: {},
                    hidden: false,
                    id: "None-0-2",
                    isArray: false,
                    isChoice: false,
                    isConfigurable: false,
                    is_ASCII: [],
                    is_ByteArray: [],
                    is_VisibleString: [],
                    maxValue: "9",
                    minValue: "0",
                    modifier: "",
                    parent: null,
                    reference: "",
                    section: "NLR",
                    title: null,
                  },
                ],
                comment: "",
                defaultValue: null,
                dtypeChoices: null,
                enumChoices: {},
                hidden: false,
                id: "None-0",
                isArray: false,
                isChoice: false,
                isConfigurable: false,
                is_ASCII: [],
                is_ByteArray: [],
                is_VisibleString: [],
                maxValue: null,
                minValue: null,
                modifier: "",
                parent: null,
                reference: "",
                section: "NLR",
                title: null,
              },
              children: [
                {
                  _dtype: "Structure",
                  arrayTemplate: null,
                  children: [
                    {
                      _dtype: "OctetStringDTO",
                      arrayTemplate: null,
                      children: [],
                      comment: "",
                      defaultValue: "0,0,0,0",
                      dtypeChoices: null,
                      enumChoices: {},
                      hidden: false,
                      id: "5-0-1-0-0",
                      isArray: false,
                      isChoice: false,
                      isConfigurable: false,
                      is_ASCII: [],
                      is_ByteArray: [],
                      is_VisibleString: [],
                      maxValue: 4,
                      minValue: 4,
                      modifier: "",
                      parent: null,
                      reference: "",
                      section: "NLR",
                      title: null,
                    },
                    {
                      _dtype: "OctetStringDTO",
                      arrayTemplate: null,
                      children: [],
                      comment: "",
                      defaultValue: "0,1,10,0,100,255",
                      dtypeChoices: null,
                      enumChoices: {},
                      hidden: false,
                      id: "5-0-1-0-1",
                      isArray: false,
                      isChoice: false,
                      isConfigurable: false,
                      is_ASCII: [],
                      is_ByteArray: [],
                      is_VisibleString: [],
                      maxValue: 6,
                      minValue: 6,
                      modifier: "",
                      parent: null,
                      reference: "",
                      section: "NLR",
                      title: "Contract1TarifficationScriptTable",
                    },
                    {
                      _dtype: "Unsigned16DTO",
                      arrayTemplate: null,
                      children: [],
                      comment: "",
                      defaultValue: "0",
                      dtypeChoices: null,
                      enumChoices: {},
                      hidden: false,
                      id: "5-0-1-0-2",
                      isArray: false,
                      isChoice: false,
                      isConfigurable: false,
                      is_ASCII: [],
                      is_ByteArray: [],
                      is_VisibleString: [],
                      maxValue: "9",
                      minValue: "0",
                      modifier: "",
                      parent: null,
                      reference: "",
                      section: "NLR",
                      title: null,
                    },
                  ],
                  comment: "",
                  defaultValue: null,
                  dtypeChoices: null,
                  enumChoices: {},
                  hidden: false,
                  id: "5-0-1-0",
                  isArray: false,
                  isChoice: false,
                  isConfigurable: false,
                  is_ASCII: [],
                  is_ByteArray: [],
                  is_VisibleString: [],
                  maxValue: null,
                  minValue: null,
                  modifier: "",
                  parent: null,
                  reference: "",
                  section: "NLR",
                  title: null,
                },
              ],
              comment: "",
              defaultValue: null,
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "5-0-1",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: "24",
              minValue: "1",
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
          ],
          comment: "",
          defaultValue: null,
          dtypeChoices: null,
          enumChoices: {},
          hidden: false,
          id: "5-0",
          isArray: false,
          isChoice: false,
          isConfigurable: false,
          is_ASCII: [],
          is_ByteArray: [],
          is_VisibleString: [],
          maxValue: null,
          minValue: null,
          modifier: "",
          parent: null,
          reference: "",
          section: "NLR",
          title: null,
        },
      ],
      comment: "",
      defaultValue: null,
      dtypeChoices: null,
      enumChoices: {},
      hidden: false,
      id: "5",
      isArray: false,
      isChoice: false,
      isConfigurable: false,
      is_ASCII: [],
      is_ByteArray: [],
      is_VisibleString: [],
      maxValue: "12",
      minValue: "1",
      modifier: "",
      parent: null,
      reference: "",
      section: "NLR",
      title: "day_profile_table_active",
    },
    {
      _dtype: "OctetStringDTO",
      arrayTemplate: null,
      children: [],
      comment: "",
      defaultValue: "115,101,97,115,111,110,95,49",
      dtypeChoices: null,
      enumChoices: {},
      hidden: false,
      id: "6",
      isArray: false,
      isChoice: false,
      isConfigurable: false,
      is_ASCII: [],
      is_ByteArray: [],
      is_VisibleString: [],
      maxValue: 8,
      minValue: 8,
      modifier: "",
      parent: null,
      reference: "",
      section: "NLR",
      title: "calendar_name_passive",
    },
    {
      _dtype: "Array",
      arrayTemplate: {
        _dtype: "Structure",
        arrayTemplate: null,
        children: [
          {
            _dtype: "OctetStringDTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "115,101,97,115,111,110,95,49",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-0",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: 8,
            minValue: 8,
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "OctetStringDTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "255,255,1,1,255,0,0,0,0,128,0,0",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-1",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: 12,
            minValue: 12,
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "OctetStringDTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "119,101,101,107,95,48,48,49",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-2",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: 8,
            minValue: 8,
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
        ],
        comment: "",
        defaultValue: null,
        dtypeChoices: null,
        enumChoices: {},
        hidden: false,
        id: "None-0",
        isArray: false,
        isChoice: false,
        isConfigurable: false,
        is_ASCII: [],
        is_ByteArray: [],
        is_VisibleString: [],
        maxValue: null,
        minValue: null,
        modifier: "",
        parent: null,
        reference: "",
        section: "NLR",
        title: null,
      },
      children: [
        {
          _dtype: "Structure",
          arrayTemplate: null,
          children: [
            {
              _dtype: "OctetStringDTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "115,101,97,115,111,110,95,49",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "7-0-0",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: 8,
              minValue: 8,
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "OctetStringDTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "255,255,1,1,255,0,0,0,0,128,0,0",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "7-0-1",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: 12,
              minValue: 12,
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "OctetStringDTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "119,101,101,107,95,48,48,49",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "7-0-2",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: 8,
              minValue: 8,
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
          ],
          comment: "",
          defaultValue: null,
          dtypeChoices: null,
          enumChoices: {},
          hidden: false,
          id: "7-0",
          isArray: false,
          isChoice: false,
          isConfigurable: false,
          is_ASCII: [],
          is_ByteArray: [],
          is_VisibleString: [],
          maxValue: null,
          minValue: null,
          modifier: "",
          parent: null,
          reference: "",
          section: "NLR",
          title: null,
        },
      ],
      comment: "",
      defaultValue: null,
      dtypeChoices: null,
      enumChoices: {},
      hidden: false,
      id: "7",
      isArray: false,
      isChoice: false,
      isConfigurable: false,
      is_ASCII: [],
      is_ByteArray: [],
      is_VisibleString: [],
      maxValue: "12",
      minValue: "1",
      modifier: "",
      parent: null,
      reference: "",
      section: "NLR",
      title: "season_profile_passive",
    },
    {
      _dtype: "Array",
      arrayTemplate: {
        _dtype: "Structure",
        arrayTemplate: null,
        children: [
          {
            _dtype: "OctetStringDTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "119,101,101,107,95,48,48,49",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-0",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: 8,
            minValue: 8,
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "Unsigned8DTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "1",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-1",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: "12",
            minValue: "1",
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "Unsigned8DTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "1",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-2",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: "12",
            minValue: "1",
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "Unsigned8DTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "1",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-3",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: "12",
            minValue: "1",
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "Unsigned8DTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "1",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-4",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: "12",
            minValue: "1",
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "Unsigned8DTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "1",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-5",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: "12",
            minValue: "1",
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "Unsigned8DTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "1",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-6",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: "12",
            minValue: "1",
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "Unsigned8DTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "1",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-7",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: "12",
            minValue: "1",
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
        ],
        comment: "",
        defaultValue: null,
        dtypeChoices: null,
        enumChoices: {},
        hidden: false,
        id: "None-0",
        isArray: false,
        isChoice: false,
        isConfigurable: false,
        is_ASCII: [],
        is_ByteArray: [],
        is_VisibleString: [],
        maxValue: null,
        minValue: null,
        modifier: "",
        parent: null,
        reference: "",
        section: "NLR",
        title: null,
      },
      children: [
        {
          _dtype: "Structure",
          arrayTemplate: null,
          children: [
            {
              _dtype: "OctetStringDTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "119,101,101,107,95,48,48,49",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "8-0-0",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: 8,
              minValue: 8,
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "Unsigned8DTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "1",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "8-0-1",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: "12",
              minValue: "1",
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "Unsigned8DTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "1",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "8-0-2",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: "12",
              minValue: "1",
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "Unsigned8DTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "1",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "8-0-3",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: "12",
              minValue: "1",
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "Unsigned8DTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "1",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "8-0-4",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: "12",
              minValue: "1",
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "Unsigned8DTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "1",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "8-0-5",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: "12",
              minValue: "1",
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "Unsigned8DTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "1",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "8-0-6",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: "12",
              minValue: "1",
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "Unsigned8DTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "1",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "8-0-7",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: "12",
              minValue: "1",
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
          ],
          comment: "",
          defaultValue: null,
          dtypeChoices: null,
          enumChoices: {},
          hidden: false,
          id: "8-0",
          isArray: false,
          isChoice: false,
          isConfigurable: false,
          is_ASCII: [],
          is_ByteArray: [],
          is_VisibleString: [],
          maxValue: null,
          minValue: null,
          modifier: "",
          parent: null,
          reference: "",
          section: "NLR",
          title: null,
        },
      ],
      comment: "",
      defaultValue: null,
      dtypeChoices: null,
      enumChoices: {},
      hidden: false,
      id: "8",
      isArray: false,
      isChoice: false,
      isConfigurable: false,
      is_ASCII: [],
      is_ByteArray: [],
      is_VisibleString: [],
      maxValue: "12",
      minValue: "1",
      modifier: "",
      parent: null,
      reference: "",
      section: "NLR",
      title: "week_profile_table_passive",
    },
    {
      _dtype: "Array",
      arrayTemplate: {
        _dtype: "Structure",
        arrayTemplate: null,
        children: [
          {
            _dtype: "Unsigned8DTO",
            arrayTemplate: null,
            children: [],
            comment: "",
            defaultValue: "1",
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-0",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: "12",
            minValue: "1",
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
          {
            _dtype: "Array",
            arrayTemplate: {
              _dtype: "Structure",
              arrayTemplate: null,
              children: [
                {
                  _dtype: "OctetStringDTO",
                  arrayTemplate: null,
                  children: [],
                  comment: "",
                  defaultValue: "0,0,0,0",
                  dtypeChoices: null,
                  enumChoices: {},
                  hidden: false,
                  id: "None-0-0",
                  isArray: false,
                  isChoice: false,
                  isConfigurable: false,
                  is_ASCII: [],
                  is_ByteArray: [],
                  is_VisibleString: [],
                  maxValue: 4,
                  minValue: 4,
                  modifier: "",
                  parent: null,
                  reference: "",
                  section: "NLR",
                  title: null,
                },
                {
                  _dtype: "OctetStringDTO",
                  arrayTemplate: null,
                  children: [],
                  comment: "",
                  defaultValue: "0,1,10,0,100,255",
                  dtypeChoices: null,
                  enumChoices: {},
                  hidden: false,
                  id: "None-0-1",
                  isArray: false,
                  isChoice: false,
                  isConfigurable: false,
                  is_ASCII: [],
                  is_ByteArray: [],
                  is_VisibleString: [],
                  maxValue: 6,
                  minValue: 6,
                  modifier: "",
                  parent: null,
                  reference: "",
                  section: "NLR",
                  title: "Contract1TarifficationScriptTable",
                },
                {
                  _dtype: "Unsigned16DTO",
                  arrayTemplate: null,
                  children: [],
                  comment: "",
                  defaultValue: "0",
                  dtypeChoices: null,
                  enumChoices: {},
                  hidden: false,
                  id: "None-0-2",
                  isArray: false,
                  isChoice: false,
                  isConfigurable: false,
                  is_ASCII: [],
                  is_ByteArray: [],
                  is_VisibleString: [],
                  maxValue: "9",
                  minValue: "0",
                  modifier: "",
                  parent: null,
                  reference: "",
                  section: "NLR",
                  title: null,
                },
              ],
              comment: "",
              defaultValue: null,
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "None-0",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: null,
              minValue: null,
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            children: [
              {
                _dtype: "Structure",
                arrayTemplate: null,
                children: [
                  {
                    _dtype: "OctetStringDTO",
                    arrayTemplate: null,
                    children: [],
                    comment: "",
                    defaultValue: "0,0,0,0",
                    dtypeChoices: null,
                    enumChoices: {},
                    hidden: false,
                    id: "None-0-1-0-0",
                    isArray: false,
                    isChoice: false,
                    isConfigurable: false,
                    is_ASCII: [],
                    is_ByteArray: [],
                    is_VisibleString: [],
                    maxValue: 4,
                    minValue: 4,
                    modifier: "",
                    parent: null,
                    reference: "",
                    section: "NLR",
                    title: null,
                  },
                  {
                    _dtype: "OctetStringDTO",
                    arrayTemplate: null,
                    children: [],
                    comment: "",
                    defaultValue: "0,1,10,0,100,255",
                    dtypeChoices: null,
                    enumChoices: {},
                    hidden: false,
                    id: "None-0-1-0-1",
                    isArray: false,
                    isChoice: false,
                    isConfigurable: false,
                    is_ASCII: [],
                    is_ByteArray: [],
                    is_VisibleString: [],
                    maxValue: 6,
                    minValue: 6,
                    modifier: "",
                    parent: null,
                    reference: "",
                    section: "NLR",
                    title: "Contract1TarifficationScriptTable",
                  },
                  {
                    _dtype: "Unsigned16DTO",
                    arrayTemplate: null,
                    children: [],
                    comment: "",
                    defaultValue: "0",
                    dtypeChoices: null,
                    enumChoices: {},
                    hidden: false,
                    id: "None-0-1-0-2",
                    isArray: false,
                    isChoice: false,
                    isConfigurable: false,
                    is_ASCII: [],
                    is_ByteArray: [],
                    is_VisibleString: [],
                    maxValue: "9",
                    minValue: "0",
                    modifier: "",
                    parent: null,
                    reference: "",
                    section: "NLR",
                    title: null,
                  },
                ],
                comment: "",
                defaultValue: null,
                dtypeChoices: null,
                enumChoices: {},
                hidden: false,
                id: "None-0-1-0",
                isArray: false,
                isChoice: false,
                isConfigurable: false,
                is_ASCII: [],
                is_ByteArray: [],
                is_VisibleString: [],
                maxValue: null,
                minValue: null,
                modifier: "",
                parent: null,
                reference: "",
                section: "NLR",
                title: null,
              },
            ],
            comment: "",
            defaultValue: null,
            dtypeChoices: null,
            enumChoices: {},
            hidden: false,
            id: "None-0-1",
            isArray: false,
            isChoice: false,
            isConfigurable: false,
            is_ASCII: [],
            is_ByteArray: [],
            is_VisibleString: [],
            maxValue: "24",
            minValue: "1",
            modifier: "",
            parent: null,
            reference: "",
            section: "NLR",
            title: null,
          },
        ],
        comment: "",
        defaultValue: null,
        dtypeChoices: null,
        enumChoices: {},
        hidden: false,
        id: "None-0",
        isArray: false,
        isChoice: false,
        isConfigurable: false,
        is_ASCII: [],
        is_ByteArray: [],
        is_VisibleString: [],
        maxValue: null,
        minValue: null,
        modifier: "",
        parent: null,
        reference: "",
        section: "NLR",
        title: null,
      },
      children: [
        {
          _dtype: "Structure",
          arrayTemplate: null,
          children: [
            {
              _dtype: "Unsigned8DTO",
              arrayTemplate: null,
              children: [],
              comment: "",
              defaultValue: "1",
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "9-0-0",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: "12",
              minValue: "1",
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
            {
              _dtype: "Array",
              arrayTemplate: {
                _dtype: "Structure",
                arrayTemplate: null,
                children: [
                  {
                    _dtype: "OctetStringDTO",
                    arrayTemplate: null,
                    children: [],
                    comment: "",
                    defaultValue: "0,0,0,0",
                    dtypeChoices: null,
                    enumChoices: {},
                    hidden: false,
                    id: "None-0-0",
                    isArray: false,
                    isChoice: false,
                    isConfigurable: false,
                    is_ASCII: [],
                    is_ByteArray: [],
                    is_VisibleString: [],
                    maxValue: 4,
                    minValue: 4,
                    modifier: "",
                    parent: null,
                    reference: "",
                    section: "NLR",
                    title: null,
                  },
                  {
                    _dtype: "OctetStringDTO",
                    arrayTemplate: null,
                    children: [],
                    comment: "",
                    defaultValue: "0,1,10,0,100,255",
                    dtypeChoices: null,
                    enumChoices: {},
                    hidden: false,
                    id: "None-0-1",
                    isArray: false,
                    isChoice: false,
                    isConfigurable: false,
                    is_ASCII: [],
                    is_ByteArray: [],
                    is_VisibleString: [],
                    maxValue: 6,
                    minValue: 6,
                    modifier: "",
                    parent: null,
                    reference: "",
                    section: "NLR",
                    title: "Contract1TarifficationScriptTable",
                  },
                  {
                    _dtype: "Unsigned16DTO",
                    arrayTemplate: null,
                    children: [],
                    comment: "",
                    defaultValue: "0",
                    dtypeChoices: null,
                    enumChoices: {},
                    hidden: false,
                    id: "None-0-2",
                    isArray: false,
                    isChoice: false,
                    isConfigurable: false,
                    is_ASCII: [],
                    is_ByteArray: [],
                    is_VisibleString: [],
                    maxValue: "9",
                    minValue: "0",
                    modifier: "",
                    parent: null,
                    reference: "",
                    section: "NLR",
                    title: null,
                  },
                ],
                comment: "",
                defaultValue: null,
                dtypeChoices: null,
                enumChoices: {},
                hidden: false,
                id: "None-0",
                isArray: false,
                isChoice: false,
                isConfigurable: false,
                is_ASCII: [],
                is_ByteArray: [],
                is_VisibleString: [],
                maxValue: null,
                minValue: null,
                modifier: "",
                parent: null,
                reference: "",
                section: "NLR",
                title: null,
              },
              children: [
                {
                  _dtype: "Structure",
                  arrayTemplate: null,
                  children: [
                    {
                      _dtype: "OctetStringDTO",
                      arrayTemplate: null,
                      children: [],
                      comment: "",
                      defaultValue: "0,0,0,0",
                      dtypeChoices: null,
                      enumChoices: {},
                      hidden: false,
                      id: "9-0-1-0-0",
                      isArray: false,
                      isChoice: false,
                      isConfigurable: false,
                      is_ASCII: [],
                      is_ByteArray: [],
                      is_VisibleString: [],
                      maxValue: 4,
                      minValue: 4,
                      modifier: "",
                      parent: null,
                      reference: "",
                      section: "NLR",
                      title: null,
                    },
                    {
                      _dtype: "OctetStringDTO",
                      arrayTemplate: null,
                      children: [],
                      comment: "",
                      defaultValue: "0,1,10,0,100,255",
                      dtypeChoices: null,
                      enumChoices: {},
                      hidden: false,
                      id: "9-0-1-0-1",
                      isArray: false,
                      isChoice: false,
                      isConfigurable: false,
                      is_ASCII: [],
                      is_ByteArray: [],
                      is_VisibleString: [],
                      maxValue: 6,
                      minValue: 6,
                      modifier: "",
                      parent: null,
                      reference: "",
                      section: "NLR",
                      title: "Contract1TarifficationScriptTable",
                    },
                    {
                      _dtype: "Unsigned16DTO",
                      arrayTemplate: null,
                      children: [],
                      comment: "",
                      defaultValue: "0",
                      dtypeChoices: null,
                      enumChoices: {},
                      hidden: false,
                      id: "9-0-1-0-2",
                      isArray: false,
                      isChoice: false,
                      isConfigurable: false,
                      is_ASCII: [],
                      is_ByteArray: [],
                      is_VisibleString: [],
                      maxValue: "9",
                      minValue: "0",
                      modifier: "",
                      parent: null,
                      reference: "",
                      section: "NLR",
                      title: null,
                    },
                  ],
                  comment: "",
                  defaultValue: null,
                  dtypeChoices: null,
                  enumChoices: {},
                  hidden: false,
                  id: "9-0-1-0",
                  isArray: false,
                  isChoice: false,
                  isConfigurable: false,
                  is_ASCII: [],
                  is_ByteArray: [],
                  is_VisibleString: [],
                  maxValue: null,
                  minValue: null,
                  modifier: "",
                  parent: null,
                  reference: "",
                  section: "NLR",
                  title: null,
                },
              ],
              comment: "",
              defaultValue: null,
              dtypeChoices: null,
              enumChoices: {},
              hidden: false,
              id: "9-0-1",
              isArray: false,
              isChoice: false,
              isConfigurable: false,
              is_ASCII: [],
              is_ByteArray: [],
              is_VisibleString: [],
              maxValue: "24",
              minValue: "1",
              modifier: "",
              parent: null,
              reference: "",
              section: "NLR",
              title: null,
            },
          ],
          comment: "",
          defaultValue: null,
          dtypeChoices: null,
          enumChoices: {},
          hidden: false,
          id: "9-0",
          isArray: false,
          isChoice: false,
          isConfigurable: false,
          is_ASCII: [],
          is_ByteArray: [],
          is_VisibleString: [],
          maxValue: null,
          minValue: null,
          modifier: "",
          parent: null,
          reference: "",
          section: "NLR",
          title: null,
        },
      ],
      comment: "",
      defaultValue: null,
      dtypeChoices: null,
      enumChoices: {},
      hidden: false,
      id: "9",
      isArray: false,
      isChoice: false,
      isConfigurable: false,
      is_ASCII: [],
      is_ByteArray: [],
      is_VisibleString: [],
      maxValue: "12",
      minValue: "1",
      modifier: "",
      parent: null,
      reference: "",
      section: "NLR",
      title: "day_profile_table_passive",
    },
    {
      _dtype: "OctetStringDTO",
      arrayTemplate: null,
      children: [],
      comment: "",
      defaultValue: "7,208,1,1,6,0,0,0,0,128,0,0",
      dtypeChoices: null,
      enumChoices: {},
      hidden: false,
      id: "10",
      isArray: false,
      isChoice: false,
      isConfigurable: false,
      is_ASCII: [],
      is_ByteArray: [],
      is_VisibleString: [],
      maxValue: 12,
      minValue: 12,
      modifier: "",
      parent: null,
      reference: "",
      section: "NLR",
      title: "activate_passive_calendar_time",
    },
  ],
  captureObject: [],
  classId: "20",
  comment: "",
  logicalName: "0;4;13;0;0;255",
  method: [
    {
      _dtype: "Integer8DTO",
      arrayTemplate: null,
      children: [],
      comment: "",
      defaultValue: "0",
      dtypeChoices: null,
      enumChoices: {},
      hidden: false,
      id: "129",
      isArray: false,
      isChoice: false,
      isConfigurable: false,
      is_ASCII: [],
      is_ByteArray: [],
      is_VisibleString: [],
      maxValue: "0",
      minValue: "0",
      modifier: "m_act_activate_passive",
      parent: null,
      reference: "",
      section: "NLR",
      title: "activate_passive_calendar",
    },
  ],
  objectName: "Contract1ActivityCalendar",
  selectedVersion: "version-0",
  templates: {},
  title: "Contract1ActivityCalendar",
};

const defaultValue = {
  workItem: dummyWorkItem_activityCalendar,
  updateWorkItem: (newWorkItem) => {
    console.warn(
      "[WorkItemContext::updateWorkItem] This function running at internal component context"
    );
    console.log(`[WorkItemContext::updateWorkItem] update work item`);
    defaultValue.workItem = newWorkItem;
  },
  activeNodeTreeId: "",
  onClicked: (node) => {
    console.warn("[WorkItemPresentationContext] you are using defalt context");
    console.log(
      `[WorkItemPresentationContext] item clicked node id ${node.id}`
    );
    defaultValue.activeNodeTreeId = node.id;
  },
};

export const WorkItemPresentationContext = createContext(defaultValue);
